# Generated by Django 3.1.1 on 2020-09-23 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(max_length=500, null=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino_set', to='usuarios.domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('duracion', models.IntegerField()),
                ('envio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='envio.envio')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('fecha_hora', models.DateTimeField()),
                ('subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envio.subasta')),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.transportista')),
            ],
        ),
        migrations.AddField(
            model_name='envio',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envio.estado'),
        ),
        migrations.AddField(
            model_name='envio',
            name='etiquetas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envio.etiqueta'),
        ),
        migrations.AddField(
            model_name='envio',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen_set', to='usuarios.domicilio'),
        ),
        migrations.AddField(
            model_name='envio',
            name='tipo_carga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.carga'),
        ),
        migrations.AddField(
            model_name='envio',
            name='trasnsportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.transportista'),
        ),
    ]
